#Add XZ CVE
#https://nvd.nist.gov/vuln/detail/CVE-2023-4911
#https://github.com/Perl/perl5/issues/16649
#CVE-2018-1000156
[capabilities]
[capabilities.cve_shell_command_injection]
predicates = ["CAP_cve_shell_command_injection"]
  binaries = [
  { name = "emacs", CVE_ID = "CVE-2023-27985", version_command = "--version", version = [
    "28.1",
    "28.2",
  ], dependencies = { files = [
    "emacsclient-mail.desktop",
  ], executables = [
  ], conditions = [
  ] } },
   # To get the version you need to use the name clamav not clamscan
  { name = "clamscam", CVE_ID = "CVE-2023-20032", version_command = "--version", version = [
    "0.103.0",
    "0.103.1",
    "0.103.2",
    "0.103.3",
    "0.103.4",
    "0.103.5",
    "0.104.*",
    "0.105.0",
    "0.105.1",
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
  ] } },
  #Fix dummy data
  { name = "gzip", CVE_ID = "CVE-2022-1271", version_command = "--version", version = [
    "1.0",
    "1.0*",
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8",
    "1.9",
    "1.10",
    "1.11",  
  ], dependencies = { files = [
  ], executables = [
    "sed",
  ], conditions = [
    { type = "user_can_create_file" }
  ] } },
  { name = "busybox", CVE_ID = "CVE-2022-30065", version_command = "| head -1", version = [
    "1.35.*",
  ], dependencies = { files = [
  ], executables = [
    "awk",
  ], conditions = [
  ] } },
  { name = "busybox", CVE_ID = "CVE-2018-1000500", version_command = "| head -1", version = [
    "1.0*.*",
    "1.1*.*",
    "1.2*.*",
    "1.31.*",
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
  ] } },
  { name = "perl", CVE_ID = "CVE-2018-18312", version_command = "--version", version = [
    "5.8.*",
    "5.1*.*",
    "5.20.*",
    "5.22.*",
    "5.24.*",
    "5.26.0",
    "5.26.1",
    "5.26.2",
    "5.28.0",
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
  ] } },
  { name = "vim", CVE_ID = "CVE-2020-20703", version_command = "--version", version = [
    "8.1.2135 ",
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
  ] } },
  { name = "patch", CVE_ID = "CVE-2018-1000156", version_command = "--version", version = [
    "2.7.6",
  ], dependencies = { files = [
  ], executables = [
    "ed",
  ], conditions = [
  ] } },
  { name = "curl", CVE_ID = "CVE-2020-8177", version_command = "--version", version = [
    "7.2*.*",
    "7.3*.*",
    "7.4*.*",
    "7.5*.*",
    "7.6*.*",
    "7.70.0",    
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
  ] } },
  { name = "ld", CVE_ID = "CVE-2018-1000876", version_command = "--version", version = [
    "2.0",
    "2.1",
    "2.3",
    "2.4",
    "2.5",
    "2.6",
    "2.7",
    "2.8",
    "2.9",
    "2.1*",
    "2.2*",
    "2.30",
    "2.31",
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
  ] } },
]
[capabilities.CAP_CVE_write_any_file]
predicates = ["CAP_CVE_write_any_file"]
binaries = [
  { name = "gzip", CVE_ID = "CVE-2022-1271", version_command = "--version", version = [
    "1.0",
    "1.0*",
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8",
    "1.9",
    "1.10",
    "1.11",
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
    { type = "user_can_create_file" }
  ] } },
  { name = "patch", CVE_ID = "CVE-2019-13636", version_command = "--version", version = [
    "2.5",
    "2.5.*",
    "2.6",
    "2.6.*",
    "2.7",
    "2.7.1",
    "2.7.2",
    "2.7.3",
    "2.7.4",
    "2.7.5",
    "2.7.6",

  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
    { type = "user_can_create_file" }
  ] } },
  { name = "curl", CVE_ID = "CVE-2020-8177", version_command = "--version", version = [
    "7.2*.*",
    "7.3*.*",
    "7.4*.*",
    "7.5*.*",
    "7.6*.*",
    "7.70.0",
  ], dependencies = { files = [
  ], executables = [
  ], conditions = [
  ] } },
]